import type { Evidence, Finding, Severity } from '../rules/types.js';
import { t, tm, type Locale } from '../i18n/index.js';
import type { ScanResult } from './model.js';

const SEV_LABEL: Record<Severity, string> = {
  critical: 'CRITICAL',
  high: 'HIGH',
  medium: 'MEDIUM',
  low: 'LOW',
};

function evidenceLine(e: Evidence, locale: Locale): string {
  switch (e.kind) {
    case 'file':
      return `\`${e.path}:${e.line}\` — ${e.excerpt}`;
    case 'http':
      return `\`${e.method} ${e.url}\` → ${e.status}${e.header ? ` (${e.header})` : ''}${e.snippet ? ` — ${e.snippet}` : ''}`;
    case 'absence':
      return `${t('engine.absence-evidence', undefined, locale)}: ${tm(e.note, locale)}`;
  }
}

export function renderMarkdown(result: ScanResult, locale: Locale): string {
  const out: string[] = [];
  const active = result.findings.filter((f) => !f.suppressed);
  const suppressed = result.findings.filter((f) => f.suppressed);
  const c = result.counts;

  out.push(`# trussary check — ${result.root}`);
  out.push('');
  out.push(`Generated by trussary ${result.tool.version} on ${result.scannedAt}.`);
  if (result.stacks.length > 0) out.push(`Stacks: ${result.stacks.join(', ')}.`);
  out.push('');
  out.push('| Severity | Count |');
  out.push('| --- | --- |');
  out.push(`| Critical | ${c.critical} |`);
  out.push(`| High | ${c.high} |`);
  out.push(`| Medium | ${c.medium} |`);
  out.push(`| Low | ${c.low} |`);
  out.push('');

  for (const f of active) {
    out.push(`## [${SEV_LABEL[f.severity]} · ${f.confidence}] ${tm(f.title, locale)}`);
    out.push('');
    out.push(`**${t('engine.why', undefined, locale)}** ${tm(f.whyItMatters, locale)}`);
    out.push('');
    out.push(`**${t('engine.evidence', undefined, locale)}** ${evidenceLine(f.evidence, locale)}`);
    out.push('');
    out.push(`**${t('engine.check', undefined, locale)}** ${tm(f.checkWhetherThisIsYou, locale)}`);
    out.push('');
    out.push(`**${t('engine.fixed-when', undefined, locale)}** ${tm(f.fixedWhen, locale)}`);
    out.push('');
    out.push(`### ${t('engine.how', undefined, locale)}`);
    out.push('');
    out.push(tm(f.howToFix, locale));
    out.push('');
    if (f.confidence === 'possible') {
      out.push(`> ${t('engine.possible-note', undefined, locale)}`);
      out.push('');
    }
  }

  if (suppressed.length > 0) {
    out.push('## Suppressed');
    out.push('');
    for (const f of suppressed) {
      const reason = f.suppressed?.reason ? ` — ${f.suppressed.reason}` : '';
      out.push(`- \`${f.id}\` (${SEV_LABEL[f.severity]}) via ${f.suppressed?.by}${reason}`);
    }
    out.push('');
  }

  if (result.liveCheck) {
    out.push('## Live check receipt');
    out.push('');
    out.push(`- URL: ${result.liveCheck.url}`);
    out.push(`- Ownership: self-asserted via \`--i-own-this-site\` at ${result.liveCheck.assertedAt}`);
    out.push(`- Requests made: ${result.liveCheck.requestsMade} (GET/HEAD only)`);
    out.push(`- Paths probed: ${result.liveCheck.pathsProbed.map((p) => `\`${p}\``).join(', ')}`);
    out.push(`- User agent: \`${result.liveCheck.userAgent}\``);
    out.push('');
  }

  out.push('---');
  out.push('');
  out.push(t('engine.cta', undefined, locale));
  out.push('');
  return out.join('\n');
}
